FROM oven/bun:latest as builder
WORKDIR /app
COPY --chown=node:node . .
RUN bun install
ENV NODE_ENV=production
RUN cd /app/manager && bun generate

FROM nginx:stable-alpine as production
COPY --from=builder /app/manager/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
